name: smartvillage
description: A new Flutter project.
publish_to: 'none'
version: 2.0.2+26

environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  package_info_plus: ^7.0.0
  shared_preferences: ^2.2.2
  http: ^1.2.1
  flutter_spinkit: ^5.2.1
  health: ^10.2.0
  flutter_phoenix: ^1.1.1
  intl: ^0.19.0
  auto_size_text: ^3.0.0
  flutter_easyloading: ^3.0.5
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  rxdart: ^0.27.7
  path_provider: ^2.1.2
  app_tracking_transparency: ^2.0.4
  background_fetch: ^1.3.2
  health_kit_reporter: ^2.1.1
  wakelock: ^0.6.2
  wakelock_windows: ^0.2.1
  firebase_core: ^2.28.0
  firebase_database: ^10.5.0
  permission_handler: ^11.3.1

dependency_overrides:
  win32: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  assets:
    - assets/
  fonts:
    - family: ArialRoundedMT
      fonts:
        - asset: fonts/sm_font_bold.ttf
          weight: 700
        - asset: fonts/sm_font.ttf
  uses-material-design: true